Repository CMU-17313Q/fall23-nodebb-generation-z, pull requests merged in 2023-10, with the labels that each got.

#31 Issue # 2 - display of announcement ion specified groups - resolved.
  src/controllers/groups.js
  src/posts/summary.js
  test/controllers.js
Labels: enhancement, User story 1, testing, Front-end, completed

#30 Testing endorsed attribute on topics & posts
  src/views/admin/partials/categories/users.tpl
  test/posts/uploads.js
  test/topics/events.js
  themes/nodebb-theme-persona/templates/category.tpl
Labels: User story 3, testing, Back-end, completed

#32 Fixing anonymous posts details - icons and displayname on group pages
  public/src/modules/helpers.common.js
  src/posts/summary.js
  themes/nodebb-theme-persona/templates/partials/posts_list_item.tpl
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
Labels: enhancement, User story 3, Front-end, completed, Sprint 2
